services:
  web:
    image: nginx:alpine
    container_name: jokenpo_dev_nginx
    restart: unless-stopped
    # Removemos a porta 'ports' aberta na rede local inteira (1234:1234)
    # Trocamos por 'expose', que abre as portas apenas na rede interna do Docker 
    # pro Cloudflare Tunnel conseguir acessar, mas bloqueia o resto da rede externa!
    expose:
      - "1234"
      - "1235"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      - ./files:/usr/share/nginx/files:ro


  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: jokenpo_tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TUNNEL_LOGLEVEL=warn